name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Python requirements
      run: |-
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Fetch and parse new captions
      run: |-
        python ./enumerate_captions.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Fetch and parse new captions" || exit 0
        git push
